version: '3'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /portainer/Files/AppData/Config/qBittorrent:/config
      - /portainer/Downloads:/downloads
    ports:
      - ${WEBUI_PORT}:8088
      - ${SERVER_PORT}:6881
      - ${SERVER_PORT}:6881/udp
    restart: unless-stopped